### ISSUE TITLE
Create mySQL instance singularity container

### ISSUE THREAD

**Issue by tomersagi** [KasperSkytte/covid19#18]
TODO

**Comment by KasperSkytte** [comment]
Hi Tomer. Just an idea if you aren't familiar with it, but maybe use GitHub Projects boards for to-do's?

**Comment by tomersagi** [comment]
Boards are for high-level tracking. The details are in the issues anyways as soon as you start working with it.

**Comment by tomersagi** [comment]
Working fine. Thanks @biocyberman !
