### ISSUE TITLE
Create data cleansing script

### ISSUE THREAD

**Issue by tomersagi** [KasperSkytte/covid19#20]
- [x] Figure out where to trigger the script -- @KasperSkytte please advise on this issue
- [x] Make list of boolean fields and look for non True/False values, convert known mistakes (0,1,Falsk, Sand), dump other non-conforming values
- [x] Check for non-dates in date fields. 
- [x] Make a list of probable data inconsistencies and check for them, e.g.  - pregnant and Male, pregnant and >45 years old / <17 years old,

**Comment by tomersagi** [comment]
List: https://github.com/KasperSkytte/covid19/wiki/data_cleansing

**Comment by biocyberman** [comment]
The team at nextrain already did [something for this purpose](https://github.com/nextstrain/ncov-ingest/blob/master/bin/transform). May be we can reuse and extend?

**Comment by tomersagi** [comment]
@biocyberman thanks, but these things are very specific to your schema and data sources. I have already finished most of the work. Just have some common sense tests left to code in.

**Comment by biocyberman** [comment]
@tomersagi Thought it's also gisaid data, but great that you got some progress already.
