### ISSUE TITLE
Metadata contains supicous pregnancy data

### ISSUE THREAD

**Issue by tomersagi** [KasperSkytte/covid19#22]
There are 102 cases of a person having Sex='M' and Pregnancy=1. Seems unreasonable. 
@TYMichaelsen maybe you can help track this down?

**Comment by tomersagi** [comment]
e.g.: SSI SSI-808, Pregnancy 1, Sex M, ReportAge 56, ReportAgeGrp 50-59

**Comment by tomersagi** [comment]
There are 102 such rows in the dataset 62 of them are not of child-bearing years

**Comment by TYMichaelsen** [comment]
That is wierd - in the complete linelist of metadata this is not an issue, only in the set we have recieved from SSI through Morten. I will ask Morten about it, also who you should contact in the future for metadata-related issues.
